# Generated by Django 4.2.4 on 2023-08-31 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PerfumeShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Products in cart'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Products in cart'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
